exclude: '^stickers\.json$'
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-docstring-first
          - id: check-yaml
          - id: debug-statements
          - id: double-quote-string-fixer
          - id: requirements-txt-fixer
    - repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            additional_dependencies: [flake8-typing-imports==1.7.0]
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.6.0
      hooks:
          - id: autopep8
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v3.1.0
      hooks:
          - id: reorder-python-imports
            args: [--py3-plus, --unclassifiable-application-module=config]
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.2.3
      hooks:
          - id: add-trailing-comma
            args: [--py36-plus]
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.34.0
      hooks:
          - id: pyupgrade
            args: [--py36-plus]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.961
      hooks:
          - id: mypy
